const vocabDB = {
    en: [
        { day: 1, word: "ubiquitous", meaning: "어디에나 있는" }, { day: 1, word: "ephemeral", meaning: "수명이 짧은, 단명하는" },
        { day: 1, word: "pragmatic", meaning: "실용적인" }, { day: 1, word: "meticulous", meaning: "꼼꼼한, 세심한" },
        { day: 1, word: "obscure", meaning: "모호한, 무명의" }, { day: 1, word: "resilient", meaning: "회복력 있는, 탄력 있는" },
        { day: 1, word: "ambiguous", meaning: "애매모호한" }, { day: 1, word: "diligent", meaning: "부지런한" },
        { day: 1, word: "lucid", meaning: "명쾌한, 맑은" }, { day: 1, word: "eloquent", meaning: "유창한, 설득력 있는" },
        { day: 2, word: "plausible", meaning: "그럴듯한, 타당한" }, { day: 2, word: "lucrative", meaning: "수익성이 좋은" },
        { day: 2, word: "obsolete", meaning: "구식의, 쓸모없게 된" }, { day: 2, word: "profound", meaning: "심오한, 깊은" },
        { day: 2, word: "tentative", meaning: "잠정적인, 머뭇거리는" }, { day: 2, word: "vulnerable", meaning: "취약한, 연약한" },
        { day: 2, word: "serene", meaning: "고요한, 평온한" }, { day: 2, word: "rigorous", meaning: "엄격한, 철저한" },
        { day: 2, word: "redundant", meaning: "불필요한, 중복되는" }, { day: 2, word: "prevalent", meaning: "널리 퍼진, 만연한" },
        { day: 3, word: "mitigate", meaning: "완화하다, 경감시키다" }, { day: 3, word: "alleviate", meaning: "고통 등을 덜다" },
        { day: 3, word: "exacerbate", meaning: "악화시키다" }, { day: 3, word: "delineate", meaning: "상세히 묘사하다" },
        { day: 3, word: "fluctuate", meaning: "변동하다, 오르내리다" }, { day: 3, word: "deviate", meaning: "벗어나다, 빗나가다" },
        { day: 3, word: "scrutinize", meaning: "면밀히 조사하다" }, { day: 3, word: "consolidate", meaning: "통합하다, 굳건히 하다" },
        { day: 3, word: "eradicate", meaning: "근절하다, 뿌리뽑다" }, { day: 3, word: "initiate", meaning: "시작하다, 개시하다" },
        { day: 4, word: "anomaly", meaning: "변칙, 이례적인 것" }, { day: 4, word: "paradigm", meaning: "패러다임, 전형적인 예" },
        { day: 4, word: "paradox", meaning: "역설, 모순" }, { day: 4, word: "arbitrary", meaning: "임의적인, 제멋대로인" },
        { day: 4, word: "empirical", meaning: "경험적인, 실증적인" }, { day: 4, word: "aesthetic", meaning: "미학적인, 심미적인" },
        { day: 4, word: "indigenous", meaning: "토착의, 고유한" }, { day: 4, word: "formidable", meaning: "가공할, 어마어마한" },
        { day: 4, word: "feasible", meaning: "실행 가능한" }, { day: 4, word: "tangible", meaning: "만질 수 있는, 실체가 있는" },
        { day: 5, word: "versatile", meaning: "다재다능한, 다용도의" }, { day: 5, word: "volatile", meaning: "변동성이 큰, 휘발성의" },
        { day: 5, word: "viable", meaning: "실행 가능한, 생존 가능한" }, { day: 5, word: "superficial", meaning: "표면적인, 피상적인" },
        { day: 5, word: "subtle", meaning: "미묘한, 감지하기 힘든" }, { day: 5, word: "spontaneous", meaning: "자발적인, 즉흥적인" },
        { day: 5, word: "simultaneous", meaning: "동시의" }, { day: 5, word: "relevant", meaning: "관련 있는, 적절한" },
        { day: 5, word: "reluctant", meaning: "꺼리는, 마지못한" }, { day: 5, word: "prominent", meaning: "저명한, 두드러진" },
        { day: 6, word: "imperative", meaning: "필수적인, 반드시 해야 하는" }, { day: 6, word: "implicit", meaning: "암시된, 내포된" },
        { day: 6, word: "explicit", meaning: "명백한, 뚜렷한" }, { day: 6, word: "inevitable", meaning: "불가피한, 필연적인" },
        { day: 6, word: "inherent", meaning: "내재하는, 본질적인" }, { day: 6, word: "intrinsic", meaning: "고유한, 본질적인" },
        { day: 6, word: "extrinsic", meaning: "외적인, 비본질적인" }, { day: 6, word: "indispensable", meaning: "없어서는 안 될, 필수적인" },
        { day: 6, word: "innate", meaning: "타고난, 선천적인" }, { day: 6, word: "trivial", meaning: "사소한, 하찮은" },
        { day: 7, word: "decipher", meaning: "해독하다" }, { day: 7, word: "deduce", meaning: "추론하다" },
        { day: 7, word: "depict", meaning: "묘사하다" }, { day: 7, word: "deter", meaning: "단념시키다, 방해하다" },
        { day: 7, word: "distract", meaning: "주의를 딴 데로 돌리다" }, { day: 7, word: "distort", meaning: "왜곡하다" },
        { day: 7, word: "disguise", meaning: "변장하다, 위장하다" }, { day: 7, word: "discern", meaning: "알아차리다, 식별하다" },
        { day: 7, word: "disperse", meaning: "흩어지다, 해산하다" }, { day: 7, word: "dissipate", meaning: "소멸되다, 낭비하다" },
        { day: 8, word: "anomaly", meaning: "이례적인 것" }, { day: 8, word: "benevolent", meaning: "자비로운" },
        { day: 8, word: "candid", meaning: "솔직한" }, { day: 8, word: "condone", meaning: "용납하다" },
        { day: 8, word: "dearth", meaning: "부족, 결핍" }, { day: 8, word: "eccentric", meaning: "별난, 기이한" },
        { day: 8, word: "fastidious", meaning: "까다로운" }, { day: 8, word: "garrulous", meaning: "수다스러운" },
        { day: 8, word: "hinder", meaning: "방해하다" }, { day: 8, word: "impartial", meaning: "공정한" },
        { day: 9, word: "lucid", meaning: "명쾌한" }, { day: 9, word: "malleable", meaning: "유연한" },
        { day: 9, word: "novel", meaning: "새로운" }, { day: 9, word: "obscure", meaning: "모호한" },
        { day: 9, word: "partisan", meaning: "편파적인" }, { day: 9, word: "quell", meaning: "진압하다" },
        { day: 9, word: "refute", meaning: "반박하다" }, { day: 9, word: "sanguine", meaning: "낙관적인" },
        { day: 9, word: "taciturn", meaning: "과묵한" }, { day: 9, word: "ubiquitous", meaning: "어디에나 있는" },
        { day: 10, word: "vacillate", meaning: "망설이다" }, { day: 10, word: "wary", meaning: "경계하는" },
        { day: 10, word: "zealous", meaning: "열성적인" }, { day: 10, word: "absolve", meaning: "용서하다" },
        { day: 10, word: "belligerent", meaning: "호전적인" }, { day: 10, word: "capricious", meaning: "변덕스러운" },
        { day: 10, word: "debilitate", meaning: "악화시키다" }, { day: 10, word: "elusive", meaning: "찾기 힘든" },
        { day: 10, word: "fallacy", meaning: "오류" }, { day: 10, word: "gregarious", meaning: "사교적인" },
        { day: 11, word: "haughty", meaning: "거만한" }, { day: 11, word: "impetuous", meaning: "성급한" },
        { day: 11, word: "jovial", meaning: "명랑한" }, { day: 11, word: "kindle", meaning: "불을 붙이다" },
        { day: 11, word: "lament", meaning: "슬퍼하다" }, { day: 11, word: "magnanimous", meaning: "관대한" },
        { day: 11, word: "nostalgia", meaning: "향수" }, { day: 11, word: "obliterate", meaning: "지우다" },
        { day: 11, word: "paramount", meaning: "최고의" }, { day: 11, word: "quandary", meaning: "진퇴양난" },
        { day: 12, word: "reclusive", meaning: "은둔하는" }, { day: 12, word: "sagacious", meaning: "현명한" },
        { day: 12, word: "tenacious", meaning: "집요한" }, { day: 12, word: "unprecedented", meaning: "전례 없는" },
        { day: 12, word: "venerate", meaning: "존경하다" }, { day: 12, word: "wan", meaning: "창백한" },
        { day: 12, word: "yield", meaning: "양보하다, 산출하다" }, { day: 12, word: "zenith", meaning: "정점" },
        { day: 12, word: "aesthetic", meaning: "미적인" }, { day: 12, word: "brevity", meaning: "간결함" },
        { day: 13, word: "corroborate", meaning: "확증하다" }, { day: 13, word: "daunting", meaning: "벅찬" },
        { day: 13, word: "embellish", meaning: "장식하다" }, { day: 13, word: "fabricate", meaning: "날조하다" },
        { day: 13, word: "gratuitous", meaning: "무료의, 불필요한" }, { day: 13, word: "hypocritical", meaning: "위선적인" },
        { day: 13, word: "illustrious", meaning: "저명한" }, { day: 13, word: "jeopardize", meaning: "위태롭게 하다" },
        { day: 13, word: "lucrative", meaning: "수익성이 좋은" }, { day: 13, word: "mundane", meaning: "평범한" },
        { day: 14, word: "nefarious", meaning: "사악한" }, { day: 14, word: "opulent", meaning: "호화로운" },
        { day: 14, word: "perplex", meaning: "당혹스럽게 하다" }, { day: 14, word: "quintessential", meaning: "전형적인" },
        { day: 14, word: "resilient", meaning: "탄력 있는" }, { day: 14, word: "sporadic", meaning: "산발적인" },
        { day: 14, word: "trepidation", meaning: "두려움" }, { day: 14, word: "usurp", meaning: "빼앗다" },
        { day: 14, word: "vindicate", meaning: "정당성을 입증하다" }, { day: 14, word: "whimsical", meaning: "기발한" }
    ],
    ja: [
        { day: 1, word: "我慢 (がまん)", meaning: "참음, 인내" }, { day: 1, word: "遠慮 (えんりょ)", meaning: "사양, 조심함" },
        { day: 1, word: "偶然 (ぐうぜん)", meaning: "우연" }, { day: 1, word: "真剣 (しんけん)", meaning: "진지함" },
        { day: 1, word: "素敵 (すてき)", meaning: "멋짐, 훌륭함" }, { day: 1, word: "贅沢 (ぜいたく)", meaning: "사치" },
        { day: 1, word: "後悔 (こうかい)", meaning: "후회" }, { day: 1, word: "迷惑 (めいわく)", meaning: "민폐" },
        { day: 1, word: "無断 (むだん)", meaning: "무단" }, { day: 1, word: "夢中 (むちゅう)", meaning: "열중함" },
        { day: 2, word: "納得 (なっとく)", meaning: "납득" }, { day: 2, word: "油断 (ゆだん)", meaning: "방심" },
        { day: 2, word: "余裕 (よゆう)", meaning: "여유" }, { day: 2, word: "冷静 (れいせい)", meaning: "냉정함" },
        { day: 2, word: "誤解 (ごかい)", meaning: "오해" }, { day: 2, word: "自慢 (じまん)", meaning: "자랑" },
        { day: 2, word: "深刻 (しんこく)", meaning: "심각함" }, { day: 2, word: "退屈 (たいくつ)", meaning: "지루함" },
        { day: 2, word: "妥協 (だきょう)", meaning: "타협" }, { day: 2, word: "同情 (どうじょう)", meaning: "동정" },
        { day: 3, word: "反省 (はんせい)", meaning: "반성" }, { day: 3, word: "不満 (ふまん)", meaning: "불만" },
        { day: 3, word: "面倒 (めんどう)", meaning: "귀찮음" }, { day: 3, word: "優秀 (ゆうしゅう)", meaning: "우수함" },
        { day: 3, word: "流行 (りゅうこう)", meaning: "유행" }, { day: 3, word: "曖昧 (あいまい)", meaning: "애매함" },
        { day: 3, word: "慰める (なぐさめる)", meaning: "위로하다" }, { day: 3, word: "怠る (おこたる)", meaning: "게을리하다" },
        { day: 3, word: "傾く (かたむく)", meaning: "기울다" }, { day: 3, word: "稼ぐ (かせぐ)", meaning: "돈を 벌다" },
        { day: 4, word: "狂う (くるう)", meaning: "미치다, 어긋나다" }, { day: 4, word: "削る (けずる)", meaning: "깎다, 삭감하다" },
        { day: 4, word: "凍える (こごえる)", meaning: "얼다" }, { day: 4, word: "逆らう (さからう)", meaning: "거스르다" },
        { day: 4, word: "沈む (しずむ)", meaning: "가라앉다" }, { day: 4, word: "従う (したがう)", meaning: "따르다" },
        { day: 4, word: "優れる (すぐれる)", meaning: "뛰어나다" }, { day: 4, word: "救う (すくう)", meaning: "구하다" },
        { day: 4, word: "責める (せめる)", meaning: "비난하다" }, { day: 4, word: "頼る (たよる)", meaning: "의지하다" },
        { day: 5, word: "誓う (ちかう)", meaning: "맹세하다" }, { day: 5, word: "捕まる (つかまる)", meaning: "붙잡히다" },
        { day: 5, word: "慰問 (いもん)", meaning: "위문" }, { day: 5, word: "輝く (かがやく)", meaning: "빛나다" },
        { day: 5, word: "隠す (かくす)", meaning: "숨기다" }, { day: 5, word: "囲む (かこむ)", meaning: "둘러싸다" },
        { day: 5, word: "悲しむ (かなしむ)", meaning: "슬퍼하다" }, { day: 5, word: "乾く (かわく)", meaning: "마르다" },
        { day: 5, word: "効く (きく)", meaning: "효과가 있다" }, { day: 5, word: "暮らす (くらす)", meaning: "생활하다" },
        { day: 6, word: "越える (こえる)", meaning: "넘다" }, { day: 6, word: "凍る (こおる)", meaning: "얼다" },
        { day: 6, word: "探す (さがす)", meaning: "찾다" }, { day: 6, word: "騒ぐ (さわぐ)", meaning: "떠들다" },
        { day: 6, word: "叱る (しかる)", meaning: "꾸짖다" }, { day: 6, word: "示す (しめす)", meaning: "가리키다, 보여주다" },
        { day: 6, word: "滑る (すべる)", meaning: "미끄러지다" }, { day: 6, word: "育つ (そだつ)", meaning: "자라다" },
        { day: 6, word: "倒す (たおす)", meaning: "쓰러뜨리다" }, { day: 6, word: "確かめる (たしかめる)", meaning: "확인하다" },
        { day: 7, word: "尋ねる (たずねる)", meaning: "묻다" }, { day: 7, word: "例える (たとえる)", meaning: "비유하다" },
        { day: 7, word: "頼む (たのむ)", meaning: "부탁하다" }, { day: 7, word: "試す (ためす)", meaning: "시험하다" },
        { day: 7, word: "違う (ちがう)", meaning: "다르다" }, { day: 7, word: "近づく (ちかづく)", meaning: "다가가다" },
        { day: 7, word: "疲れる (つかれる)", meaning: "지치다" }, { day: 7, word: "伝える (つたえる)", meaning: "전하다" },
        { day: 7, word: "続く (つづく)", meaning: "계속되다" }, { day: 7, word: "包む (つつむ)", meaning: "싸다, 포장하다" }
    ],
    zh: [
        { day: 1, word: "坚持 (jiānchí)", meaning: "고집하다, 견지하다" }, { day: 1, word: "放弃 (fàngqì)", meaning: "포기하다" },
        { day: 1, word: "经验 (jīngyàn)", meaning: "경험" }, { day: 1, word: "解决 (jiějué)", meaning: "해결하다" },
        { day: 1, word: "理解 (lǐjiě)", meaning: "이해하다" }, { day: 1, word: "努力 (nǔlì)", meaning: "노력하다" },
        { day: 1, word: "其实 (qíshí)", meaning: "사실은" }, { day: 1, word: "情况 (qíngkuàng)", meaning: "상황" },
        { day: 1, word: "认为 (rènwéi)", meaning: "여기다, 생각하다" }, { day: 1, word: "如果 (rúguǒ)", meaning: "만약" },
        { day: 2, word: "虽然 (suīrán)", meaning: "비록 ~일지라도" }, { day: 2, word: "特别 (tèbié)", meaning: "특별히" },
        { day: 2, word: "提供 (tígōng)", meaning: "제공하다" }, { day: 2, word: "希望 (xīwàng)", meaning: "희망하다" },
        { day: 2, word: "需要 (xūyào)", meaning: "필요하다" }, { day: 2, word: "选择 (xuǎnzé)", meaning: "선택하다" },
        { day: 2, word: "一直 (yìzhí)", meaning: "줄곧" }, { day: 2, word: "影响 (yǐngxiǎng)", meaning: "영향" },
        { day: 2, word: "遇到 (yùdào)", meaning: "우연히 만나다" }, { day: 2, word: "愿意 (yuànyì)", meaning: "원하다" },
        { day: 3, word: "真正 (zhēnzhèng)", meaning: "진정한" }, { day: 3, word: "只要 (zhǐyào)", meaning: "오직 ~하기만 하면" },
        { day: 3, word: "注意 (zhùyì)", meaning: "주의하다" }, { day: 3, word: "总是 (zǒngshì)", meaning: "항상" },
        { day: 3, word: "作用 (zuòyòng)", meaning: "작용, 역할" }, { day: 3, word: "安全 (ānquán)", meaning: "안전하다" },
        { day: 3, word: "保证 (bǎozhèng)", meaning: "보증하다" }, { day: 3, word: "报道 (bàodào)", meaning: "보도하다" },
        { day: 3, word: "标准 (biāozhǔn)", meaning: "표준" }, { day: 3, word: "表达 (biǎodá)", meaning: "표현하다" },
        { day: 4, word: "表面 (biǎomiàn)", meaning: "표면" }, { day: 4, word: "表明 (biǎomíng)", meaning: "분명히 나타내다" },
        { day: 4, word: "表现 (biǎoxiàn)", meaning: "표현, 태도" }, { day: 4, word: "并且 (bìngqiě)", meaning: "게다가" },
        { day: 4, word: "不但 (búdàn)", meaning: "단지 ~뿐만 아니라" }, { day: 4, word: "不可思议 (bùkěsīyì)", meaning: "불가사의하다" },
        { day: 4, word: "不然 (bùrán)", meaning: "그렇지 않으면" }, { day: 4, word: "不足 (bùzú)", meaning: "부족하다" },
        { day: 4, word: "部分 (bùfen)", meaning: "부분" }, { day: 4, word: "材料 (cáiliào)", meaning: "재료" },
        { day: 5, word: "采取 (cǎiqǔ)", meaning: "채택하다" }, { day: 5, word: "测验 (cèyàn)", meaning: "측정하다" },
        { day: 5, word: "产生 (chǎnshēng)", meaning: "발생하다" }, { day: 5, word: "超过 (chāoguò)", meaning: "초과하다" },
        { day: 5, word: "成功 (chénggōng)", meaning: "성공하다" }, { day: 5, word: "成为 (chéngwéi)", meaning: "~이 되다" },
        { day: 5, word: "诚实 (chéngshí)", meaning: "성실하다" }, { day: 5, word: "承担 (chéngdān)", meaning: "담당하다" },
        { day: 5, word: "承认 (chéngrèn)", meaning: "승인하다" }, { day: 5, word: "程度 (chéngdù)", meaning: "정도" },
        { day: 6, word: "吃惊 (chījīng)", meaning: "놀라다" }, { day: 6, word: "充满 (chōngmǎn)", meaning: "충만하다" },
        { day: 6, word: "抽空 (chōukòng)", meaning: "틈을 내다" }, { day: 6, word: "出门 (chūmén)", meaning: "외출하다" },
        { day: 6, word: "出现 (chūxiàn)", meaning: "출현하다" }, { day: 6, word: "除了 (chúle)", meaning: "~을 제외하고" },
        { day: 6, word: "处理 (chǔlǐ)", meaning: "처리하다" }, { day: 6, word: "传真 (chuánzhēn)", meaning: "팩스" },
        { day: 6, word: "窗户 (chuānghu)", meaning: "창문" }, { day: 6, word: "词语 (cíyǔ)", meaning: "어휘" },
        { day: 7, word: "从来 (cónglái)", meaning: "여태껏" }, { day: 7, word: "错误 (cuòwù)", meaning: "잘못, 오류" },
        { day: 7, word: "达到 (dádào)", meaning: "도달하다" }, { day: 7, word: "打破 (dǎpò)", meaning: "타파하다" },
        { day: 7, word: "大概 (dàgài)", meaning: "대개, 아마" }, { day: 7, word: "代表 (dàibiǎo)", meaning: "대표하다" },
        { day: 7, word: "大夫 (dàifu)", meaning: "의사" }, { day: 7, word: "代替 (dàitì)", meaning: "대체하다" },
        { day: 7, word: "当 (dāng)", meaning: "~할 때, ~이 되다" }, { day: 14, word: "到底 (dàodǐ)", meaning: "도대체" }
    ]
};

if (typeof module !== 'undefined' && module.exports) {
    module.exports = vocabDB;
}
